/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-07-19 09:05:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bottom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("\tpadding: 15px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tbackground: #ed6161;\r\n");
      out.write("}\r\n");
      out.write(".inDiv{\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 380px;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write(".inDiv img {margin-top: 10px;}\r\n");
      out.write(".inDiv a {color: white;}\r\n");
      out.write(".inDiv .adviceTel {font-size: 30px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"height: 250px;\"></div>\r\n");
      out.write("\t<div class=\"footer\" align=\"center\" >\r\n");
      out.write("\t\t<div style=\"width:1400px; margin: auto;\">\r\n");
      out.write("\t\t\t<div class=\"inDiv\" style=\"width: 200px;\">\r\n");
      out.write("\t\t\t\t<img src=\"/img/logo_ver3.png\" width=\"150px;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inDiv\">\r\n");
      out.write("\t\t\t\tCOMPANY. (주)빨간맛 <br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\tE-MAIL. email@mail.com <br>\r\n");
      out.write("\t\t\t\tADDRESS. 44693 111, Samsan-ro, Nam-gu, Ulsan, Republic of Korea <br>\r\n");
      out.write("\t\t\t\tBUSINESS LICENSE. 123-12-12345 <br>\r\n");
      out.write("\t\t\t\tMAIL-ORDER LICENSE. 제1234호-울산삼산-12345호  <br>\r\n");
      out.write("\t\t\t\t개인정보 보호 책임자. RED <br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inDiv\">\r\n");
      out.write("\t\t\t\t교환/반품 주소.<br>\t\t\t\t\r\n");
      out.write("\t\t\t\t울산광역시 남구 달동 645-11 현은빌딩 5층 <br>\r\n");
      out.write("\t\t\t\t(도로명 주소 : 울산광역시 남구 달동 삼산로 111 (우) 44693) <br>\r\n");
      out.write("\t\t\t\t국민 123456-12-123456<br>\r\n");
      out.write("\t\t\t\t농협 123-1234-1234-12<br>\r\n");
      out.write("\t\t\t\t신한 123-123-123456<br>\r\n");
      out.write("\t\t\t\t기업 123-123456-12-123<br>\r\n");
      out.write("\t\t\t\t예금주 : (주)빨간맛<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inDiv\" style=\"width: 300px;\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t고객센터 <span class=\"adviceTel\">1544-2767</span><br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t평일 9:00 ~ 18:00 / 점심시간 12:00~13:00<br>\r\n");
      out.write("\t\t\t\t<a href=\"#\">1:1 상담신청 &gt;</a><br>\r\n");
      out.write("\t\t\t\t주말 및 공휴일은 1:1상담을 이용해주세요.<br>\r\n");
      out.write("\t\t\t\t1:1상담은 로그인 후 이용가능 합니다.<br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t\t<div align=\"center\" style=\"font-size: small;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">COMPANY INFO</td>\r\n");
      out.write("\t\t\t\t\t<td>C.S CENTER</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\tCOMPANY. (주)빨간맛 <br>\r\n");
      out.write("\t\t\t\t\t\tTEL: 1544-5252 <br>\r\n");
      out.write("\t\t\t\t\t\tE-MAIL. email@mail.com <br>\r\n");
      out.write("\t\t\t\t\t\tADDRESS. 44693 111, Samsan-ro, Nam-gu, Ulsan, Republic of Korea <br>\r\n");
      out.write("\t\t\t\t\t\tOWNER. RED <br>\r\n");
      out.write("\t\t\t\t\t\tBUSINESS LICENSE. 123-12-12345 <br>\r\n");
      out.write("\t\t\t\t\t\tMAIL-ORDER LICENSE. 제1234호-울산삼산-12345호  <br>\r\n");
      out.write("\t\t\t\t\t\t개인정보 보호 책임자. RED <br>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t교환/반품 주소.<br>\r\n");
      out.write("\t\t\t\t\t\t울산광역시 남구 달동 645-11 현은빌딩 5층 <br>\r\n");
      out.write("\t\t\t\t\t\t(도로명 주소 : 울산광역시 남구 달동 삼산로 111 (우) 44693) <br>\r\n");
      out.write("\t\t\t\t\t\t(CJ 대한통운 1588-1255) <br>\r\n");
      out.write("\t\t\t\t\t\t타택배 반품 주소. <br>\r\n");
      out.write("\t\t\t\t\t\t울산광역시 남구 달동 645-11 현은빌딩 5층 <br>\r\n");
      out.write("\t\t\t\t\t\t(도로명 주소 : 울산광역시 남구 달동 삼산로 111 (우) 44693) <br>\r\n");
      out.write("\t\t\t\t\t\tCOPYRIGHT(C) 2019 SAPPUN. ALL RIGHT RESERVED. <br>\r\n");
      out.write("\t\t\t\t\t\tHOSTING BY (주)빨간맛닷컴 MAKESHOP <br>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t1544-2767<br>\r\n");
      out.write("\t\t\t\t\t\tMON - FRI AM 10:00 ~ PM 05:00<br>\r\n");
      out.write("\t\t\t\t\t\tLUNCH PM 01:00 ~ PM 02:00<br>\r\n");
      out.write("\t\t\t\t\t\tSAT / SUN / HOLIDAY OFF<br>\r\n");
      out.write("\t\t\t\t\t\t국민 123456-12-123456<br>\r\n");
      out.write("\t\t\t\t\t\t농협 123-1234-1234-12<br>\r\n");
      out.write("\t\t\t\t\t\t신한 123-123-123456<br>\r\n");
      out.write("\t\t\t\t\t\t기업 123-123456-12-123<br>\r\n");
      out.write("\t\t\t\t\t\t예금주 : (주)빨간맛<br>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
