/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-07-19 09:13:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fpage_005fmodal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>리뷰 모달창</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$( \"#dialog\" ).dialog({\r\n");
      out.write("\t\t\theight : \"400\",\r\n");
      out.write("\t\t\twidth : \"600\",\r\n");
      out.write("\t\t\tautoOpen: false,\r\n");
      out.write("      \t\tdraggable: false,\r\n");
      out.write("      \t\tshow: {\r\n");
      out.write("        \t\teffect: \"fade\",\r\n");
      out.write("      \t \t\tduration: 100\r\n");
      out.write("      \t\t},\r\n");
      out.write("      \t\thide: {\r\n");
      out.write("        \t\teffect: \"fade\",\r\n");
      out.write("        \t\tduration: 100\r\n");
      out.write("      \t\t}\r\n");
      out.write("    \t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write(" \r\n");
      out.write("\t\t$( \".opener\" ).on( \"click\", function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar idResult = $(this).attr('id');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (idResult == 'reviewInset') {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar itemCode = $(this).attr('data-itemCode');\r\n");
      out.write("\t\t\t\tvar itemName = $(this).attr('data-itemName');\r\n");
      out.write("\t\t\t\tvar itemPrice = $(this).attr('data-itemPrice');\t\t\t\r\n");
      out.write("\t\t\t\tvar options = $(this).attr('data-options');\r\n");
      out.write("\t\t\t\tvar itemCount = $(this).attr('data-itemCount');\r\n");
      out.write("\t\t\t\tvar itemThumbnail = $(this).attr('data-itemThumbnail');\r\n");
      out.write("\t\t\t\tvar buyCode = $(this).attr('data-buyCode');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#buyCode').val(buyCode);\r\n");
      out.write("\t\t\t\t$('#itemCode').val(itemCode);\r\n");
      out.write("\t\t\t\t$('#itemName').text(itemName);\r\n");
      out.write("\t\t\t\t$('#itemPrice').text(itemPrice + '원');\r\n");
      out.write("\t\t\t\t$('#options').text(options);\r\n");
      out.write("\t\t\t\t$('#itemCount').text(itemCount + '개');\r\n");
      out.write("\t\t\t\t$('#itemThumbnail').prop( 'src' , '../img/'+ itemThumbnail +'' );\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#btnDiv').empty();\r\n");
      out.write("\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\tstr += '<button id=\"reviewInsertBtn\">등록</button>' ;\r\n");
      out.write("\t\t\t\t$('#btnDiv').append(str);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$( \"#dialog\" ).dialog( \"open\" );\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else if (idResult == 'reviewUpdate') {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar boardCode = $(this).attr('data-boardCode');\r\n");
      out.write("\t\t\t\tvar boardTitle = $(this).attr('data-boardTitle');\r\n");
      out.write("\t\t\t\tvar boardContent = $(this).attr('data-boardContent');\r\n");
      out.write("\t\t\t\tvar boardScore = $(this).attr('data-boardScore');\r\n");
      out.write("\t\t\t\tvar itemName = $(this).attr('data-itemName');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#itemPrice').text('');\r\n");
      out.write("\t\t\t\t$('#options').text('');\r\n");
      out.write("\t\t\t\t$('#itemCount').text('');\r\n");
      out.write("\t\t\t\t$('#itemThumbnail').prop('src' , '');\r\n");
      out.write("\t\t\t\t$('#itemCode').val('');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#'+boardScore+'').parent().children('span').removeClass('on');\r\n");
      out.write("\t\t\t\t$('#'+boardScore+'').addClass('on').prevAll('span').addClass('on');\r\n");
      out.write("\t\t\t\t$('input[value=\"'+ boardTitle +'\"]').prop('checked' , true);\r\n");
      out.write("\t\t\t\t$('#boardCode').val(boardCode);\r\n");
      out.write("\t\t\t\t$('#boardContent').val(boardContent);\r\n");
      out.write("\t\t\t\t$('#itemName').text(itemName);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#btnDiv').empty();\r\n");
      out.write("\t\t\t\tvar str = '';\r\n");
      out.write("\t\t\t\tstr += '<button id=\"reviewUpdateBtn\">수정</button>' ;\r\n");
      out.write("\t\t\t\t$('#btnDiv').append(str);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$( \"#dialog\" ).dialog( \"open\" );\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write(" \t\t});\r\n");
      out.write(" \t\r\n");
      out.write("\t\tvar star = 1;\r\n");
      out.write("\t$('.starRev span').click(function(){\r\n");
      out.write("\t\t  $(this).parent().children('span').removeClass('on');\r\n");
      out.write("\t\t  $(this).addClass('on').prevAll('span').addClass('on');\r\n");
      out.write("\t\t  star = $(this).attr('id');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//리뷰 인서트 버튼 작동\r\n");
      out.write("\t$(document).on('click' , '#reviewInsertBtn' ,function(){\r\n");
      out.write("\t\tvar boardContent = $('#boardContent').val();\r\n");
      out.write("\t\tvar boardTitle =$('input[name=\"radio\"]:checked').val();\r\n");
      out.write("\t\tvar itemCode = $('#itemCode').val();\r\n");
      out.write("\t\tvar buyCode = $('#buyCode').val();\r\n");
      out.write("\t\tvar boardScore = star;\r\n");
      out.write("\t\tvar boardCategoryCode = 3;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (boardContent != '') {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: 'boardInset.do',\r\n");
      out.write("\t\t\t\ttype: 'post',\r\n");
      out.write("\t\t\t\tdata: {boardContent , boardTitle , itemCode , boardScore , boardCategoryCode , buyCode},\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\t$( \"#dialog\" ).dialog( \"close\" );\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(){\r\n");
      out.write("\t\t\t\t\talert('fail');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\talert('상품평을 입력해 주세요.');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//리뷰 업데이트 버튼 작동\r\n");
      out.write("\t$(document).on('click' , '#reviewUpdateBtn' ,function(){\r\n");
      out.write("\t\tvar boardContent = $('#boardContent').val();\r\n");
      out.write("\t\tvar boardTitle =$('input[name=\"radio\"]:checked').val();\r\n");
      out.write("\t\tvar boardCode = $('#boardCode').val();\r\n");
      out.write("\t\tvar boardScore = $('.on').length;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: 'reviewUpdate.do',\r\n");
      out.write("\t\t\ttype: 'post',\r\n");
      out.write("\t\t\tdata: {boardContent ,boardTitle ,boardCode ,boardScore },\r\n");
      out.write("\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t$( \"#dialog\" ).dialog( \"close\" );\r\n");
      out.write("\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(){\r\n");
      out.write("\t\t\t\talert('fail');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("} );\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".starR{\r\n");
      out.write("  background: url('http://miuu227.godohosting.com/images/icon/ico_review.png') no-repeat right 0;\r\n");
      out.write("  background-size: auto 100%;\r\n");
      out.write("  width: 30px;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-indent: -9999px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".starR.on{background-position:0 0;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("<div align=\"center\" id=\"dialog\" title=\"상품 리뷰 쓰기\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"itemCode\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"buyCode\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"boardCode\">\r\n");
      out.write("\t\t<img alt=\"\" id=\"itemThumbnail\" src=\"\" style=\"width: 50px; height: 50px;\">\r\n");
      out.write("\t\t<label id=\"itemName\"></label><br>\r\n");
      out.write("\t\t<label id=\"itemPrice\"></label> /\r\n");
      out.write("\t\t<label id=\"itemCount\"></label> /\r\n");
      out.write("\t\t<label id=\"options\"></label>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t상품\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"radioReview\" id=\"radio1\" name=\"radio\" value=\"만족\" checked><label for=\"radio1\">만족</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"radioReview\" id=\"radio2\" name=\"radio\" value=\"보통\"><label for=\"radio2\" >보통</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"radioReview\" id=\"radio3\" name=\"radio\" value=\"불만\"><label for=\"radio3\" >불만</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>만족도</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"starRev\">\r\n");
      out.write("\t\t\t\t\t  <span class=\"starR on\" id=\"1\">별1</span>\r\n");
      out.write("\t\t\t\t\t  <span class=\"starR\" id=\"2\">별2</span>\r\n");
      out.write("\t\t\t\t\t  <span class=\"starR\" id=\"3\">별3</span>\r\n");
      out.write("\t\t\t\t\t  <span class=\"starR\" id=\"4\">별4</span>\r\n");
      out.write("\t\t\t\t\t  <span class=\"starR\" id=\"5\">별5</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>상품평</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"boardContent\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table><br>\r\n");
      out.write("\t\t<div id=\"btnDiv\">\r\n");
      out.write("\t\t\t<button id=\"reviewInsertBtn\">확인</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
