/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-04-02 10:34:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ddmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Menucool ddmenu</title>\r\n");
      out.write("    <link href=\"../css/ddmenu.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <script src=\"../js/ddmenu.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t<nav id=\"ddmenu\">\r\n");
      out.write("\t    <div class=\"menu-icon\"></div>\r\n");
      out.write("\t    <ul>\r\n");
      out.write("\t        <li class=\"full-width\">\r\n");
      out.write("\t            <span class=\"top-heading\">Unde Omnis</span>\r\n");
      out.write("\t            <i class=\"caret\"></i>\r\n");
      out.write("\t            <div class=\"dropdown\">\r\n");
      out.write("\t                <div class=\"dd-inner\">\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Lorem Ipsum</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Dolor sit amet</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Consectetur elit</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Etiam massa</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Suscipit sapien</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Quis turpis</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Etiam Massa</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Sed interdum</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Fringilla congue</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Dolor nisl auctor</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Quisque dictum</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Porttitor</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    <ul class=\"column mayHide\">\r\n");
      out.write("\t                        <li><br /><img src=\"img/img1.jpg\" /></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"no-sub\"><a class=\"top-heading\" href=\"http://www.google.com\">Quisque</a></li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t            <a class=\"top-heading\" href=\"http://www.microsoft.com\">Link</a>\r\n");
      out.write("\t            <i class=\"caret\"></i>\r\n");
      out.write("\t            <div class=\"dropdown\">\r\n");
      out.write("\t                <div class=\"dd-inner\">\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Vestibulum Ut</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Nunc pharetra</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Vestibulum ante</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Nulla id laoreet</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Elementum blandit</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t            <span class=\"top-heading\">Accusantium</span>\r\n");
      out.write("\t            <i class=\"caret\"></i>\r\n");
      out.write("\t            <div class=\"dropdown offset300\">\r\n");
      out.write("\t                <div class=\"dd-inner\">\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Pellentesque</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Fermentum ut nulla</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Duis ut mauris</a></li>\r\n");
      out.write("\t                        <li><h3>Volutpat</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Quisque dictum</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Nulla scelerisque</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Suspendisse</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Suspendisse potenti</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Curabitur in mauris</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Phasellus ultrices</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Quisque ornare</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Vestibulum</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Vitae tempus risus</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    <ul class=\"column mayHide\">\r\n");
      out.write("\t                        <li><br /><img src=\"img/img2.jpg\" /></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li class=\"no-sub\">\r\n");
      out.write("\t            <a class=\"top-heading\" href=\"#\">Dignissim</a>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t        <li>\r\n");
      out.write("\t            <span class=\"top-heading\">Laudantium</span>\r\n");
      out.write("\t            <i class=\"caret\"></i>\r\n");
      out.write("\t            <div class=\"dropdown right-aligned\">\r\n");
      out.write("\t                <div class=\"dd-inner\">\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Nam a leo</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Vel faucibus leo</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Duis ut mauris</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">In tempus semper</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">laoreet erat</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                    <ul class=\"column\">\r\n");
      out.write("\t                        <li><h3>Proin iaculis</h3></li>\r\n");
      out.write("\t                        <li><a href=\"#\">In tempus semper</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Hendrerit tincidunt</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">Duis ut mauris</a></li>\r\n");
      out.write("\t                        <li><a href=\"#\">pretium amet</a></li>\r\n");
      out.write("\t                    </ul>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </li>\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
